core/urls.py
from django.contrib import admin
from django.urls import path,include

from core import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fileflow.urls')),
]
# STATIC va MEDIA fayllarni faqat "DEBUG=True" bo'lsa ishlatish
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fileflow/urls.py
# from django.urls import path
# from . import views  # views.py dan funksiyalarni import qilish

# urlpatterns = [
#     path('', views.home, name='home'),  # Asosiy sahifa (localhost:8000/)
#     
    
   
# ]

from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views
from .views import (
    PositionListView, PositionCreateView, PositionUpdateView, PositionDeleteView,
    EmployeeListView, EmployeeCreateView, EmployeeUpdateView, EmployeeDeleteView
)

from .views import (
    PartnerListView, PartnerCreateView, PartnerUpdateView, PartnerDeleteView
)


from .views import (
    PersonDetailsListView, 
    PersonDetailsCreateView, 
    PersonDetailsUpdateView, 
    PersonDetailsDeleteView
)

urlpatterns = [
     # Login sahifasi
    path('login/', LoginView.as_view( next_page='protected'), name='login'),
    # Logout
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),

    path('', views.index, name='home'),
    # path('login/', views.login, name='login'),  # localhost:8000/login/
    path('about/', views.about, name='about'),  # localhost:8000/about/
    path('team/', views.team, name='team'),  # localhost:8000/team/
    path('contact/', views.contact, name='contact'),  # localhost:8000/contact/
    path('services/', views.services, name='services'),  # localhost:8000/services/
]

urlpatterns += [
    path('protected/', views.protected_view, name='protected'),


    # Do'stlar uchun URL'lar
    path('friends/', views.friend_list, name='friend_list'),
    path('friends/add/', views.add_friend, name='add_friend'),
    path('friends/update/<int:pk>/', views.update_friend, name='update_friend'),
    path('friends/delete/<int:pk>/', views.delete_friend, name='delete_friend'),

    # Personlar uchun URL'lar
    path('persons/', views.person_list, name='person_list'),
    path('persons/add/', views.add_person, name='add_person'),
    path('persons/update/<int:pk>/', views.update_person, name='update_person'),
    path('persons/delete/<int:pk>/', views.delete_person, name='delete_person'),
]


urlpatterns += [
    # Position URLs
    path('position/', PositionListView.as_view(), name='position_list'),
    path('position/add/', PositionCreateView.as_view(), name='position_add'),
    path('position/<int:pk>/update/', PositionUpdateView.as_view(), name='position_update'),
    path('position/<int:pk>/delete/', PositionDeleteView.as_view(), name='position_delete'),

    # Employee URLs
    path('employee/', EmployeeListView.as_view(), name='employee_list'),
    path('employee/add/', EmployeeCreateView.as_view(), name='employee_add'),
    path('employee/<int:pk>/update/', EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/<int:pk>/delete/', EmployeeDeleteView.as_view(), name='employee_delete'),
]





urlpatterns += [
    path('partner/', PartnerListView.as_view(), name='partner_list'),
    path('partner/add/', PartnerCreateView.as_view(), name='partner_add'),
    path('partner/<int:pk>/update/', PartnerUpdateView.as_view(), name='partner_update'),
    path('partner/<int:pk>/delete/', PartnerDeleteView.as_view(), name='partner_delete'),
]





urlpatterns += [
    path('person-details/', PersonDetailsListView.as_view(), name='person-details-list'),
    path('person-details/add/', PersonDetailsCreateView.as_view(), name='person-details-add'),
    path('person-details/<int:pk>/update/', PersonDetailsUpdateView.as_view(), name='person-details-update'),
    path('person-details/<int:pk>/delete/', PersonDetailsDeleteView.as_view(), name='person-details-delete'),
]

fileflow/models.py
from django.db import models
from django.contrib.auth.models import User  # Django ichki foydalanuvchi modeli

# Create your models here.

class Friend(models.Model):
    firstname = models.CharField(max_length=200)  # Ismi
    lastname = models.CharField(max_length=200)  # Familiyasi
    surename = models.CharField(max_length=200)  # Otasini ishmi
    type = models.CharField(max_length=200)  # Turi
    status = models.CharField(max_length=45, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active')
    delete = models.CharField(max_length=45, choices=[('delete', 'Restore'), ('ondelete', 'Delete')], default='delete')
    created_at = models.DateTimeField(auto_now_add=True)   # Yaratilgan vaqt
    updated_at = models.DateTimeField(auto_now=True)       # Yangilangan vaqt
    
    def __str__(self):
        return self.firstname  # Admin panelda sarlavha ko'rsatiladi


class Partner(models.Model):
    firstname = models.CharField(max_length=200)  # Ismi
    lastname = models.CharField(max_length=200)  # Familiyasi
    surename = models.CharField(max_length=200)  # Otasini ishmi
    type = models.CharField(max_length=200)  # Turi
    status = models.CharField(max_length=45, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active')
    delete = models.CharField(max_length=45, choices=[('delete', 'Restore'), ('ondelete', 'Delete')], default='delete')
    created_at = models.DateTimeField(auto_now_add=True)   # Yaratilgan vaqt
    updated_at = models.DateTimeField(auto_now=True)       # Yangilangan vaqt
    
    def __str__(self):
        return self.firstname  # Admin panelda sarlavha ko'rsatiladi




class Position(models.Model):
    POSITION_LEVEL_CHOICES = [
        ('JR', 'Junior'),         # Boshlang‘ich daraja
        ('MD', 'Mid-level'),      # O‘rta daraja
        ('SR', 'Senior'),         # Katta mutaxassis
        ('LD', 'Lead'),           # Jamoa yetakchisi
        ('EX', 'Executive'),      # Rahbariyat darajasi
    ]

    title = models.CharField(max_length=100)  # Pozitsiya nomi
    level = models.CharField(
        max_length=2,
        choices=POSITION_LEVEL_CHOICES,       # Tanlash uchun darajalar
        default='JR'                          # Standart daraja
    )
    department = models.CharField(max_length=100)  # Bo'lim nomi (Masalan, IT, HR)
    description = models.TextField(blank=True, null=True)  # Pozitsiya haqida batafsil ma'lumot
    created_at = models.DateTimeField(auto_now_add=True)   # Yaratilgan vaqt
    updated_at = models.DateTimeField(auto_now=True)       # Yangilangan vaqt
    status = models.CharField(max_length=45, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active')
    delete = models.CharField(max_length=45, choices=[('delete', 'Restore'), ('ondelete', 'Delete')], default='delete')

    def __str__(self):
        return f"{self.title} ({self.get_level_display()})"
    

class Employee(models.Model):
    firstname = models.CharField(max_length=200)  # Ismi
    lastname = models.CharField(max_length=200)  # Familiyasi
    surename = models.CharField(max_length=200)  # Otasini ishmi
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    status = models.CharField(max_length=45, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active')
    delete = models.CharField(max_length=45, choices=[('delete', 'Restore'), ('ondelete', 'Delete')], default='delete')
    created_at = models.DateTimeField(auto_now_add=True)   # Yaratilgan vaqt
    updated_at = models.DateTimeField(auto_now=True)       # Yangilangan vaqt
    def __str__(self):
        return self.firstname  # Admin panelda sarlavha ko'rsatiladi
    



class Person(models.Model):
    STATUS_CHOICES = [
        ('NEW', 'Yangi'),          # Hujjat yangi yaratilgan
        ('IN_REVIEW', 'Ko‘rib chiqilmoqda'), # Hujjat ko‘rib chiqilayotgan holatda
        ('APPROVED', 'Tasdiqlangan'),  # Hujjat tasdiqlangan
        ('REJECTED', 'Rad etilgan'),   # Hujjat rad etilgan
    ]

    firstname = models.CharField(max_length=200)  # Ismi
    lastname = models.CharField(max_length=200)  # Familiyasi
    surename = models.CharField(max_length=200)  # Otasini ishmi
    brithday=models.DateField(null=True, blank=True) # tugulgan sanasi
    type = models.CharField(max_length=200)  # Turi
    send =  models.CharField(
        max_length=20,                       # Maksimal uzunlik
        choices=STATUS_CHOICES,              # Tanlovlar
        default='NEW'                        # Standart qiymat
    )
    senddata = models.DateTimeField(auto_now_add=True)  # Yaratilgan sana vaqti
    sendstatus= models.CharField(
        max_length=20,                       # Maksimal uzunlik
        choices=STATUS_CHOICES,              # Tanlovlar
        default='NEW'                        # Standart qiymat
    )

    employee = models.ManyToManyField(Employee, related_name='Employees') 
    friend = models.ManyToManyField(Friend, related_name='Friend') 
    partner = models.ManyToManyField(Partner, related_name='Partner') 
    created_at = models.DateTimeField(auto_now_add=True)  # Yaratilgan sana vaqti
    updated_at = models.DateTimeField(auto_now=True)  # So'nggi tahrirlangan sana vaqti
    is_published = models.CharField(max_length=45, choices=[('publish', 'Published'), ('draf', 'Draf')], default='publish')  # Nashr etilganligi

    document = models.FileField(upload_to='documents/', null=True, blank=True)  # Fayl qo'shish
    image = models.ImageField(upload_to='images/', null=True, blank=True)  # Rasm qo'shish
    status = models.CharField(max_length=45, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active')
    delete = models.CharField(max_length=45, choices=[('delete', 'Restore'), ('ondelete', 'Delete')], default='delete')

   
    def __str__(self):
        return self.firstname  # Admin panelda sarlavha ko'rsatiladi
    
class PersonDetails(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='details')  # Many-to-One bog‘lanish
    el1 = models.DecimalField(max_digits=20, decimal_places=4)  
    el2 = models.DecimalField(max_digits=20, decimal_places=4)  
    created_at = models.DateTimeField(auto_now_add=True)  # Qo‘shilgan vaqti
    updated_at = models.DateTimeField(auto_now=True)  

    def __str__(self):
        return f"{self.person.firstname} - el1: {self.el1}, el2: {self.el2}"

fileflow/forms.py
from django import forms
from .models import Person, Friend

# Person uchun forma
class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['firstname', 'lastname', 'surename', 'type', 'send', 'sendstatus',  'document', 'image']

# Friend uchun forma
class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['firstname', 'lastname', 'surename', 'type', 'status']

fileflow/templates/employee_delete.html
{% extends 'base.html' %}
{% block content %}


<div class="services_section layout_padding">
    <div class="container">
        <div class="delete-page">
                <h2>"{{ object.firstname }} {{ object.lastname }}" xodimini o‘chirmoqchimisiz?</h2>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn-delete mt-2">Ha, o‘chirish</button>
                    <a href="{% url 'employee_list' %}" class="btn-submit mt-3">Yo‘q, ortga qaytish</a>
                </form>
                
        </div>
    </div>
</div>
{% endblock %}

fileflow/templates/employee_list.html
{% extends 'base.html' %}
{% block content %}


<div class="people-list-page" style="margin-bottom: 15px;">
    <h2>Xodimlar ro‘yxati</h2>
    <a href="{% url 'protected' %} " class="btn-custom btn-home m-2">Home</a>
    <a href="{% url 'employee_add' %}" class="btn-custom btn-friends m-2">+ Yangi xodim qo‘shish</a>


    <div class=" table table-bordered table-hover">
        <table class="person-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Ismi</th>
                    <th>Familiyasi</th>
                    <th>Lavozimi</th>
                    <th>Amallar</th>
                    <th>Amallar</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td>{{ employee.id }}</td>
                    <td>{{ employee.firstname }}</td>
                    <td>{{ employee.lastname }}</td>
                    <td>{{ employee.position.title }}</td>
                    <td class="actions">
                        <a href="{% url 'employee_update' employee.id %}" class="btn-action update">Yangilash</a> 
                    </td>
                    <td class="actions">
                        <a href="{% url 'employee_delete' employee.id %}" class="btn-action delete">O'chirish</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

fileflow/templates/friend_add.html
{% extends 'base.html' %}

{% block content %}
  <div class="add-friend-page">
    <h2>Do'st qo'shish</h2>
    <form method="post" class="add-friend-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn-save">Saqlash</button>
    </form>
  </div>
{% endblock %}

fileflow/templates/friend_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="delete-friend-page">
    <h2>{{ friend.firstname }}'ni o'chirish</h2>
    <form method="post" class="delete-friend-form">
      {% csrf_token %}
      <p>Bu do'stni o'chirishni xohlaysizmi?</p>
      <button type="submit" class="btn-delete">O'chirish</button>
    </form>
  </div>
{% endblock %}

fileflow/templates/friend_update.html
{% extends 'base.html' %}

{% block content %}
<div class="update-friend-page">
  <h2>Do'stni Yangilash</h2>
  <form method="post" class="update-friend-form">
    {% csrf_token %}
    <div class="form-group">
      {{ form.as_p }}
    </div>
    <button type="submit" class="btn-submit">Yangilash</button>
  </form>
</div>
{% endblock %}

fileflow/templates/partner_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="services_section layout_padding">
    <div class="container">
        <div class="delete-page">
            <h2>"{{ object.firstname }} {{ object.lastname }}" hamkorini o‘chirmoqchimisiz?</h2>
            <form method="post">
                {% csrf_token %}
                <button type="submit" style="padding: 10px 20px; background: red; color: white;">Ha, o‘chirish</button>
            </form>
            <a href="{% url 'partner_list' %}" style="display: block; margin-top: 10px; text-align: center; padding: 10px; background: gray; color: white;">Yo‘q, ortga qaytish</a>
        </div>
    </div>
</div>





{% endblock %}

fileflow/templates/partner_list.html
{% extends 'base.html' %}
{% block content %}


<div class="people-list-page" style="margin-bottom: 15px;">
    <h2>Hamkorlar ro‘yxati</h2>
    <a href="{% url 'protected' %} " class="btn-custom btn-home m-2">Home</a>
    <a href="{% url 'employee_add' %}" class="btn-custom btn-friends m-2">+ Yangi xodim qo‘shish</a>


    <div class=" table table-bordered table-hover">
        <table class="person-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Ismi</th>
                    <th>Familiyasi</th>
                    <th>Lavozimi</th>
                    <th>Amallar</th>
                    <th>Amallar</th>
                </tr>
            </thead>
            <tbody>
                {% for partner in partners %}
                <tr>
                    <td>{{ partner.id }}</td>
                    <td>{{  partner.firstname }}</td>
                    <td>{{ partner.lastname }}</td>
                    <td>{{ partner.type }}</td>
                    <td class="actions">
                        <a href="{% url 'partner_update' partner.id %}" style="display: inline-block; margin-left: 10px; padding: 5px 10px; background: yellow;">Tahrirlash</a>
                    </td>
                    <td class="actions">
                        <a href="{% url 'partner_delete' partner.id %}" style="display: inline-block; padding: 5px 10px; background: red; color: white;">O‘chirish</a>
   
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>







{% endblock %}

fileflow/templates/person_details_form.html
{% extends 'base.html' %}
{% block content %}
<div class="form-wrapper" style="margin: 30px auto;">
    
        <h2>Tafsilotlarni kiriting</h2>
        <form method="post" enctype="multipart/form-data"  class="styled-form m-4">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" style="padding: 10px 20px; background: green; color: white;">Saqlash</button>
        </form>
        <a href="{% url 'person-details-list' %}" style="display: block; margin-top: 10px; text-align: center; padding: 10px; background: gray; color: white;">Ortga qaytish</a>
</div>
{% endblock %}

fileflow/templates/person_update.html
{% extends 'base.html' %}

{% block content %}

<div class="form-wrapper">
  <h2>Personni yangilash</h2>

  <form method="post" enctype="multipart/form-data" class="styled-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn-submit">Yangilash</button>
  </form>

  
    
  </div>


{% endblock %}

fileflow/templates/position_delete.html
{% extends 'base.html' %}
{% block content %}


<div class="services_section layout_padding">
    <div class="container">
        <div class="delete-page">
            <h2>"{{ object.title }}" pozitsiyasini o‘chirmoqchimisiz?</h2>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn-delete mt-2">Ha, o‘chirish</button>
                <a href="{% url 'position_list' %}" class="btn-submit mt-3">Yo‘q, ortga qaytish</a>
            </form>
            
        </div>
    </div>
</div>
{% endblock %}

fileflow/templates/position_list.html
{% extends 'base.html' %}
{% block content %}


<div class="people-list-page" style="margin-bottom: 15px;">
    <h2>Pozitsiyalar ro‘yxati</h2>
    <a href="{% url 'protected' %} " class="btn-custom btn-home m-2">Home</a>
    <a href="{% url 'position_add' %}" class="btn-custom btn-friends m-2">+ Yangi position qo‘shish</a>


    <div class=" table table-bordered table-hover">
        <table class="person-table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nomi</th>
                    <th>Darajasi</th>
                    <th>Amallar</th>
                    <th>Amallar</th>
                </tr>
            </thead>
            <tbody>
                {% for position in positions %}
                <tr>
                    <td>{{ position.id }}</td>
                    <td>{{ position.title }}</td>
                    <td>{{ position.get_level_display }}</td>
                    <td class="actions">
                        <a href="{% url 'position_update' position.id %}" class="btn-action update">Yangilash</a>
                    </td>   
                    <td class="actions">
                        <a href="{% url 'position_delete' position.id %}" class="btn-action delete">O'chirish</a>
                    </td>           
                </tr>
                {% endfor %}
            </tbody>    
        </table>
    </div>
</div>
{% endblock %}

fileflow/templates/protected_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Personlar{% endblock %}
<!-- style css -->


{% block content %}
<div class="person-page">
    <h2>Personlar</h2>
    
    <div style="margin-bottom: 15px;">
        <a href="{% url 'friend_list' %}" class="btn-custom btn-friends">Friends</a>
        <a href="{% url 'employee_list' %}" class="btn-custom btn-employees">Employees</a>
        <a href="{% url 'position_list' %}" class="btn-custom btn-position">Positions</a>
        <a href="{% url 'partner_list' %}" class="btn-custom btn-partners">Partners</a>
        <a href="{% url 'person_list' %}" class="btn-custom btn-persons">Persons</a>
        <a href="{% url 'person-details-list' %}" class="btn-custom btn-persons-detail">Persons Details</a>
        <a href="{% url 'logout' %}" class="btn-custom btn-persons-detail">LogOut</a>
    </div>

    <div class="filter-form">
        <form method="get" action="">
          <div class="filters">
            <div class="filter-item">
                <label for="firstname">Ism:</label>
                <input type="text" name="firstname" id="firstname" value="{{ request.GET.firstname }}" placeholder="Ism bo'yicha">
            </div>
        
            <div class="filter-item">
                <label for="lastname">Familiya:</label>
                <input type="text" name="lastname" id="lastname" value="{{ request.GET.lastname }}" placeholder="Familiya bo'yicha">
            </div>
        
            <div class="filter-item">
                <label for="surename">Otasining ismi:</label>
                <input type="text" name="surename" id="surename" value="{{ request.GET.surename }}" placeholder="Otasining ismi bo'yicha">
            </div>
        
            <div class="filter-item">
                <label for="is_published">Nashr etilgan:</label>
                <select name="is_published" id="is_published">
                    <option value="">Holat</option>
                    <option value="true" {% if request.GET.is_published == 'true' %}selected{% endif %}>Ha</option>
                    <option value="false" {% if request.GET.is_published == 'false' %}selected{% endif %}>Yo'q</option>
                </select>
            </div>
        
            <div class="filter-item">
                <label for="sendstatus">Status:</label>
                <select name="sendstatus" id="sendstatus">
                    <option value="">Statusni tanlang</option>
                    <option value="NEW" {% if request.GET.sendstatus == 'NEW' %}selected{% endif %}>Yangi</option>
                    <option value="IN_REVIEW" {% if request.GET.sendstatus == 'IN_REVIEW' %}selected{% endif %}>Ko‘rib chiqilmoqda</option>
                    <option value="APPROVED" {% if request.GET.sendstatus == 'APPROVED' %}selected{% endif %}>Tasdiqlangan</option>
                    <option value="REJECTED" {% if request.GET.sendstatus == 'REJECTED' %}selected{% endif %}>Rad etilgan</option>
                </select>
            </div>
        
            <button type="submit">Filtrlash</button>
        </div>
        
        </form>
      </div>

    <div class=" table table-bordered table-hover">
        <table class="person-table">
            <thead>
                <tr>
                    <th>Number</th>
                    <th  >Familiyasi</th>
                    <th>Ismi</th>
                    <th>Otasi</th>
                    <th>Type</th>
                    <th>Send</th>
                    <th>Sendstatus</th>
                    <th>Employees</th>
                    <th>Friends</th>
                    <th>Partner</th>
                    <th>El1</th>
                    <th>El2</th>
                    <th>Is published</th>
                    <th>Document</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody  >
                {% for person in persons %}
                <tr  >
                    <td>{{ person.id }}</td>
                    <td>{{ person.lastname }}</td>
                    <td>{{ person.firstname }}</td>
                    <td>{{ person.surename }}</td>
                    <td>{{ person.type }}</td>
                    <td>{{ person.send }}</td>
                    <td>{{ person.sendstatus }}</td>
                    <td>
                        <ul>
                            {% for employee in person.persons.all %}
                            <li>{{ employee.firstname }} - {{ employee.position }}</li>
                            {% empty %}
                            <li>Hech qanday employee mavjud emas.</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul>
                            {% for friend in person.friend.all %}
                            <li>{{ friend.firstname }} - {{ friend.type }}</li>
                            {% empty %}
                            <li>Hech qanday friend mavjud emas.</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul>
                            {% for partner in person.partner.all %}
                            <li>{{ partner.firstname }} - {{ partner.type }}</li>
                            {% empty %}
                            <li>Hech qanday partner mavjud emas.</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        {% with details=person.details.all %}
                            {% if details %}
                                {% for detail in details %}
                                    {{ forloop.counter }}. {{ detail.el1 }}<br>
                                {% endfor %}
                            {% else %}
                                Mavjud emas
                            {% endif %}
                        {% endwith %}
                    </td>
                    <td>                                                
                        {% with details=person.details.all %}
                            {% if details %}
                                {% for detail in details %}
                                    {{ forloop.counter }}. {{ detail.el2 }}<br>
                                {% endfor %}
                            {% else %}
                                Mavjud emas
                            {% endif %}
                        {% endwith %}
                    </td>
                    <td>{{ person.get_is_published_display }}</td>
                    <td>
                        {% if person.document %}
                            <a href="{{ person.document.url }}" download class="btn-download">Yuklab olish</a>
                        {% else %}
                            Hujjat mavjud emas
                        {% endif %}
                    </td>

                    <td>
                        
                        {% if person.image %}
                            <a href="{{ person.image.url }}" download>
                                <img src="{{ person.image.url }}" alt="Person Image" class="person-img">
                            </a>
                        {% else %}
                            Rasm mavjud emas
                        {% endif %}
                    </td>
                </tr>

                {% empty %}
                <tr>
                    <td colspan="15" class="no-data">Hech qanday person mavjud emas.</td>
                </tr>
                {% endfor %}

            </tbody>
            <tfoot>
                <tr>
                    <td colspan="15">Page {{ persons.number }} of {{ persons.paginator.num_pages }}</td>
                </tr>
                <tr>
                    <td colspan="15">
                        {% if persons.has_previous %}
                        <a href="?page={{ persons.previous_page_number }}" class="pagination-btn">Previous</a>
                        {% endif %}
                        |
                        {% if persons.has_next %}
                        <a href="?page={{ persons.next_page_number }}" class="pagination-btn">Next</a>
                        {% endif %}
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>
{% endblock %}

fileflow/templates/services.html
{% extends "base.html" %}
{% load static %}

{% block title %}Services - My Django Site{% endblock %}

{% block content %}


    <!--services section start -->
    <div class="what_we_do_section layout_padding">
        <div class="container">
          <h1 class="what_taital">WHAT WE DO</h1>
          <p class="what_text">It is a long established fact that a reader will be distracted by the readable content of a </p>
          <div class="what_we_do_section_2">
            <div class="row">
            <div class="col-lg-3 col-sm-6">
              <div class="box_main">
                <div class="icon_1"><img src="{% static 'images/icon-1.png' %}"></div>
                <h3 class="accounting_text">Accounting</h3>
                <p class="lorem_text">Lorem Ipsum is simply dummy text of the printing and</p>
                <div class="moremore_bt_1"><a href="#">Read More </a></div>
              </div>
            </div>
            <div class="col-lg-3 col-sm-6">
              <div class="box_main active">
                <div class="icon_1"><img src="{% static 'images/icon-2.png' %}"></div>
                <h3 class="accounting_text">Advisor</h3>
                <p class="lorem_text">Lorem Ipsum is simply dummy text of the printing and</p>
                <div class="moremore_bt_1"><a href="#">Read More </a></div>
              </div>
            </div>
            <div class="col-lg-3 col-sm-6">
              <div class="box_main">
                <div class="icon_1"><img src="{% static 'images/icon-3.png' %}"></div>
                <h3 class="accounting_text">Investment</h3>
                <p class="lorem_text">Lorem Ipsum is simply dummy text of the printing and</p>
                <div class="moremore_bt_1"><a href="#">Read More </a></div>
              </div>
            </div>
            <div class="col-lg-3 col-sm-6">
              <div class="box_main">
                <div class="icon_1"><img src="{% static 'images/icon-4.png' %}"></div>
                <h3 class="accounting_text">Financial</h3>
                <p class="lorem_text">Lorem Ipsum is simply dummy text of the printing and</p>
                <div class="moremore_bt_1"><a href="#">Read More </a></div>
              </div>
            </div>
          </div>
          </div>
        </div>
      </div>
      <!--services section end -->
      

{% endblock %}